
version: '3.7'

services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    container_name: teslodb
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
    - ./postgres-data:/var/lib/postgresql/data 777
    ports:
      - 5432:5432